local cmp = {}

local c = require("nord.colors").palette

function cmp.highlights()
  return {
    CmpItemAbbrDeprecated = { fg = c.polar_night.light },
    CmpItemAbbrMatch = { fg = c.frost.ice, bold = true },
    CmpItemAbbrMatchFuzzy = { fg = c.frost.ice, bold = true },
    CmpItemMenu = { fg = c.light_grey, italic = true },
    CmpBorder = { fg = c.polar_night.brightest, bg = c.polar_night.darker },
    CmpDoc = { bg = c.polar_night.darker },
    CmpDocBorder = { fg = c.polar_night.brightest, bg = c.polar_night.darker },
    CmpPmenu = { bg = c.polar_night.darker },
    CmpSel = { link = "PmenuSel", bold = true },
    -- cmp item kinds
    CmpItemKind = { fg = c.frost.artic_water },
    CmpItemKindConstant = { fg = c.frost.artic_water },
    CmpItemKindFunction = { fg = c.frost.artic_water },
    CmpItemKindIdentifier = { fg = c.frost.ice },
    CmpItemKindField = { fg = c.frost.ice },
    CmpItemKindVariable = { fg = c.frost.artic_water },
    CmpItemKindSnippet = { fg = c.aurora.red },
    CmpItemKindText = { fg = c.white }, -- de-emphasize buf text options
    CmpItemKindStructure = { fg = c.frost.artic_water },
    CmpItemKindType = { fg = c.frost.ice },
    CmpItemKindKeyword = { fg = c.frost.polar_water },
    CmpItemKindMethod = { fg = c.frost.artic_water },
    CmpItemKindConstructor = { fg = c.blue },
    CmpItemKindFolder = { fg = c.frost.polar_water },
    CmpItemKindModule = { fg = c.frost.ice },
    CmpItemKindProperty = { fg = c.frost.ice },
    CmpItemKindEnum = { fg = c.blue },
    CmpItemKindUnit = { fg = c.frost.artic_water },
    CmpItemKindClass = { fg = c.teal },
    CmpItemKindFile = { fg = c.frost.polar_water },
    CmpItemKindInterface = { fg = c.aurora.green },
    CmpItemKindColor = { fg = c.white },
    CmpItemKindReference = { fg = c.snow_storm.brighter },
    CmpItemKindEnumMember = { fg = c.aurora.purple },
    CmpItemKindStruct = { fg = c.frost.artic_water },
    CmpItemKindValue = { fg = c.polar_water },
    CmpItemKindEvent = { fg = c.aurora.yellow },
    CmpItemKindOperator = { fg = c.snow_storm.brighter },
    CmpItemKindTypeParameter = { fg = c.frost.ice },
    CmpItemKindCopilot = { fg = c.aurora.green },

    CodeiumSuggestion = { fg = c.polar_night.light },

    BlinkCmpMenuBorder = { fg = c.polar_night.bright },
    BlinkCmpMenuSelection = { fg = c.none, bg = c.polar_night.brighter },
    BlinkCmpLabelDeprecated = { fg = c.polar_night.light },
    BlinkCmpLabelMatch = { fg = c.polar_night.ice, bold = true },
    BlinkCmpGhostText = { fg = c.polar_night.light },
    BlinkCmpDocBorder = { fg = c.polar_night.bright },
    BlinkCmpSignatureHelpBorder = { fg = c.polar_night.bright },
    BlinkCmpKindArray = { link = "@lsp.type.array" },
    BlinkCmpKindBoolean = { link = "@lsp.type.boolean" },
    BlinkCmpKindClass = { link = "@lsp.type.class" },
    BlinkCmpKindColor = { link = "@lsp.type.color" },
    BlinkCmpKindConstant = { link = "@lsp.type.constant" },
    BlinkCmpKindConstructor = { link = "@lsp.type.constructor" },
    BlinkCmpKindEnum = { link = "@lsp.type.enum" },
    BlinkCmpKindEnumMember = { link = "@lsp.type.enumMember" },
    BlinkCmpKindEvent = { link = "@lsp.type.event" },
    BlinkCmpKindField = { link = "@lsp.type.field" },
    BlinkCmpKindFile = { link = "@lsp.type.file" },
    BlinkCmpKindFolder = { link = "@lsp.type.folder" },
    BlinkCmpKindFunction = { link = "@lsp.type.function" },
    BlinkCmpKindInterface = { link = "@lsp.type.interface" },
    BlinkCmpKindKey = { link = "@lsp.type.key" },
    BlinkCmpKindKeyword = { link = "@lsp.type.keyword" },
    BlinkCmpKindMethod = { link = "@lsp.type.method" },
    BlinkCmpKindModule = { link = "@lsp.type.module" },
    BlinkCmpKindNamespace = { link = "@lsp.type.namespace" },
    BlinkCmpKindNull = { link = "@lsp.type.null" },
    BlinkCmpKindNumber = { link = "@lsp.type.number" },
    BlinkCmpKindObject = { link = "@lsp.type.object" },
    BlinkCmpKindOperator = { link = "@lsp.type.operator" },
    BlinkCmpKindPackage = { link = "@lsp.type.package" },
    BlinkCmpKindProperty = { link = "@lsp.type.property" },
    BlinkCmpKindReference = { link = "@lsp.type.reference" },
    BlinkCmpKindSnippet = { fg = c.aurora.green },
    BlinkCmpKindString = { link = "@lsp.type.string" },
    BlinkCmpKindStruct = { link = "@lsp.type.struct" },
    BlinkCmpKindText = { link = "@lsp.type.text" },
    BlinkCmpKindTypeParameter = { link = "@lsp.type.typeParameter" },
    BlinkCmpKindUnit = { link = "@lsp.type.unit" },
    BlinkCmpKindValue = { link = "@lsp.type.value" },
    BlinkCmpKindVariable = { link = "@lsp.type.variable" },

    BlinkCmpKindCodeium = { fg = c.aurora.green },
    BlinkCmpKindCopilot = { fg = c.aurora.green },
    BlinkCmpKind = { fg = c.frost.artic_water },
  }
end

return cmp
